import Head from 'next/head';
import Link from 'next/link';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { wrapper } from '../redux/store';
import { TEST1,selectAllData } from '../redux/test1/test1';

function Home({ pageProps }) {
  const  data1  = useSelector(selectAllData);

  return (
    <div>
      <h1>INDEX PAGE</h1>
      <Link href="/test">
        <a>test</a>
      </Link>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <br />
      <br />
      {data1 && data1.slice(0, 2).map((name) => <h1>{name.title}</h1>)}

      <br />
      {/* <span>{loading}</span> */}
      
 
    </div>
  );
}

export const getStaticProps = wrapper.getStaticProps(
  (store) => async (context) => {
    await store.dispatch(TEST1('1'));

    return {
      props: {},
    };
  }
);

// Home.getInitialProps = wrapper.getInitialPageProps(
//   ({ dispatch }) =>
//     async () => {
//       await dispatch(TEST1('1'));
//       return {
//         props: {},
//       };
//     }
// );

export default Home;
