# Generated by Django 4.0.4 on 2022-04-27 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='الاسم يجب ان يتكون من احرف و ارقام', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
